### PR TITLE
Fix retreat playbook link

### PR DESCRIPTION
**Pull request by benhylau**

### CODE REVIEW

**Comment by dcwalk** [comment]
Links still not working, I thought the link was updated in https://github.com/hyphacoop/shortlinks/pull/27?

**Comment by benhylau** [comment]
GitHub Actions has a re-run button, I re-run it and now it works. Shortlinks doesn't rebuild on commit, it rebuilds nightly. I wish we could make it rebuild immediately. cc. @patcon

**Comment by dcwalk** [comment]
yes I re-ran, but I guess I didn't realize shortlinks were nightly :disappointed:

**Comment by patcon** [comment]
Ah def thought it was running more than nightly! Bumped to every 30 min for now, but feedback welcome: https://github.com/hyphacoop/worker-coop-scripts/pull/8

**Pull request merged**
