### PR TITLE
Update deploy process

### LINKED ISSUE #26: Refine circle ci deploy
Deploying the handbook landed in #17 and f776d1439, but noticing some refinements need to happen:

- fix cache errors in `build-docs` workflow (aka I think this is just adding package.json) (see [recent example](https://circleci.com/gh/hyphacoop/handbook/11?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link))
- ~address something about how the gh-pages branch is both behind and ahead?~ nvm! was thinking abt this wrong
- **stretch** add new testing workflow with some sort of initial implementation of link checking or proofing?

### PR DESCRIPTION
**Pull request by dcwalk**
Closes #26 by:

- [x] adding `package.json` in order to (hopefully) fix cache errors in `build-docs` workflow (see [recent example](https://circleci.com/gh/hyphacoop/handbook/11)
- [x] updates automatic build email to `infra@` vs `noreply@`
- [x] adding `htmlproofer` testing step

### CODE REVIEW

**Comment by dcwalk** [comment]
@patcon could I get a review on this? I feel like this isn't well done but it seems like some things I'd expect to rely on circle ci for I cant (e.g., trigger builds on PRs)

**Comment by patcon** [comment]
Hm. Seems related to this..?
https://circleci.com/blog/deep-diving-into-circleci-workspaces/

**Comment by patcon** [comment]
ok, got it working. main issue with workspaces was that i was trying to use $BRANCH var in the setup up the workspace steps, and envvars couldn't be used there. I changed to just persisting to ~/workspace and not using ~/$BRANCH for folder dir

**Comment by patcon** [comment]
For next time, some samples with github actions that seems much simpler:
https://github.com/JamesIves/github-pages-deploy-action/issues/106#issuecomment-571641126

(let's stick with what we have in circleci since it's just about solved now :) )

**Comment by patcon** [comment]
holy eff i dislike circleci right now. getting some random cruft in the workspace that isn't going away

**Comment by patcon** [comment]
CircleCI was frustrating, so switched to GitHub actions, which looks cleaner.

You can see success of PR test workflow above.
Demo of success of master deploy workflow can be seen here on fork (no key or extra setup requires, since github actions get a transient token to act on the repo via API):
https://github.com/patcon/hyphacoop-handbook/actions?query=workflow%3A%22Deploy+to+GitHub+Pages%22

If it looks alright, then just delete the circleCI files and it's good to go. (or +1 and i can do it)

**Comment by patcon** [comment]
yeah, i'd chosen circleci in past for 1) being able to start workflows/jobs from API, and 2) reliable cron scheduling. those were useful for some past use-cases, but not for everyday.

i'm down to walk away from circleci for traditional stuff, toward travis or github actions.

Removed circleci config. Waiting review from dc

**Comment by patcon** [comment]
Ah, that's a bummer dc. I'm really sorry. Your feelings are understandable. In retrospect, I think I was just trying to get in a win before I went to bed, after already spending what felt like way too much time on CircleCI.

As for GitHub Actions, I just found a package that seemed to address this style of deploy that I'd never done myself. And was perhaps charmed by how composable it seemed.

I genuinely did spent a good chunk of time on your tactic first! Then I hit a wall with an issue I couldn't explain. Felt like I'd pushed you toward CircleCI through an earlier convo, so I felt guilty for the time we'd both spent. Guess I felt there was a subtext that this was stuck until I could help fix it, so just changed up tactic to unblock.

Next time maybe I could make a point to call you and rubberduck first before deciding to change tactics? Or that I would always call the owner to speak synchronously before doing something like this? (I get really exasperated working alone, and I think that's when I do this sort of rash do-over thing.)

**Comment by patcon** [comment]
Ugh. Seeing that i unassigned you. yeah, looking back, it must've felt really not cool. Thanks for helping me see this.

**Comment by patcon** [comment]
Another thoughts came to mind: Should I have another approach I'd like to try, I should take it to another branch/PR.

I should take efforts to avoid (1) unassigning someone without asking, or (2) overriding someone's work branch.

**Comment by dcwalk** [comment]
I can't actually approve this PR because I opened it, but @patcon you should feel free to merge given two +1s

I don't think the other stuff is major, wasn't sure whether to voice it and I think we can speak to any thoughts on approaches and etiquette later. I'm not too worried about it. #ops

**Pull request merged**
