### PR TITLE
Update fiscal-sponsorship.md

### PR DESCRIPTION
**Pull request by benhylau**

### CODE REVIEW

**Comment by patcon** [comment]
Left comment here by accident: https://github.com/hyphacoop/organizing/issues/336#issuecomment-726483439

No block

**Review by patcon — APPROVED** [review]

**Comment by patcon** [comment]
At risk of repeating (when I haven't yet gotten back to gdoc), moderate feelings we should attrib ocnz here. Attrib is important imho, and this isn't the same legal doc feel, but our weirdo public facing version where we get to make our own expectations :)

**Comment by benhylau** [comment]
>4. **Some header.** <a name="some-header">#</a> Blah blah

Let's keep the plain text version free of HTML. I prefer the format as is rather than having 16 headers.

>moderate feelings we should attrib ocnz here

I alrdy responded in gdoc before, that they asked not to be attributed. See email thread with Alanna.

**Comment by patcon** [comment]
kk ack, do it, but again feeling you prioritizing cleanness and format over human usability (linking to parts of large legal doc), which i am flagging as in clash with my values on these things. good to merge tho

**Review by 1atAlcone — APPROVED** [review]

**Pull request merged**
